# **Proyecto: Sistema Híbrido de Predicción y Gestión de Riesgo (FNN + GARCH)**

    Diana Denise Valdivia Vargas
    Rafael Takata García
    Daniela de la Torre Gallo
    Aissa Berenice Gonzáles Fosado

El activo elegido para este estudio es el aluminio, un commodity industrial de gran relevancia por su amplia utilización en sectores como la construcción, el transporte, el empaque y la manufactura. Su precio está influenciado por factores como la oferta global, la demanda industrial, los costos energéticos y las condiciones macroeconómicas, lo que lo convierte en un activo interesante para analizar desde una perspectiva financiera y de riesgo. Además, al tratarse de un commodity con variaciones frecuentes en su precio, representa un buen caso de estudio para aplicar modelos predictivos y de volatilidad. La motivación principal de este trabajo es mostrar cómo un Hedge Fund podría usar herramientas FFNN y GARCH para apoyar sus decisiones de inversión.

In [1]:
import pandas as pd

In [3]:
datos = pd.read_csv(r"Aluminium Historical Data.csv")
columns = ['Date', 'Price']
datos = datos[columns]
datos

            Date     Price
0     04/02/2026  3,468.50
1     04/01/2026  3,523.80
2     03/31/2026  3,429.55
3     03/30/2026  3,431.50
4     03/27/2026  3,275.20
...          ...       ...
1065  01/14/2022  2,976.50
1066  01/13/2022  2,952.00
1067  01/12/2022  2,982.50
1068  01/11/2022  2,970.00
1069  01/10/2022  2,931.50

[1070 rows x 2 columns]

In [10]:
datos['Date'] = pd.to_datetime(datos['Date'], dayfirst=False)
datos

           Date     Price
0    2026-04-02  3,468.50
1    2026-04-01  3,523.80
2    2026-03-31  3,429.55
3    2026-03-30  3,431.50
4    2026-03-27  3,275.20
...         ...       ...
1065 2022-01-14  2,976.50
1066 2022-01-13  2,952.00
1067 2022-01-12  2,982.50
1068 2022-01-11  2,970.00
1069 2022-01-10  2,931.50

[1070 rows x 2 columns]

In [14]:
fechas_correctas = pd.date_range(start='2022-01-01', end='2026-04-02')
fechas_faltantes = len(datos[~datos['Date'].isin(fechas_correctas)])
print(f"Fechas faltantes: {fechas_faltantes}")

Fechas faltantes: 0